version: '3'

services:
  postgresql:
    container_name: postgres-grpc-todo-cli

    image: postgres:15-alpine

    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: todo_list

    networks:
      - grpc-todo-cli-network

    ports:
      - "127.0.0.1:5432:5432"

    volumes:
      - grpc-todo-cli-postgres:/var/lib/postgresql/data

  adminer:
    container_name: adminer

    image: adminer:latest

    ports:
      - "127.0.0.1:8080:8080"

    restart: always

    networks:
      - grpc-todo-cli-network

networks:
  grpc-todo-cli-network:
    driver: bridge

volumes:
  grpc-todo-cli-postgres:
